from .GAN_Generator import GAN_Generator
from .DCGAN_Generator import DCGAN_Generator
from .FCL_Classical_Discriminator1 import FCL_Classical_Discriminator1
from .CNN_Classical_Discriminator1 import CNN_Classical_Discriminator1
from .QuantumDiscriminator1 import QuantumDiscriminator1
from .HybridQuantumDiscriminator1 import HybridQuantumDiscriminator1